version: '3.4'
services:
  cougarcs-backend:
    image: node:12-alpine
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: logs
        target: /app/logs
        volume:
          nocopy: true
    working_dir: /app
    command: yarn server
    ports:
      - '4000:4000'
    env_file:
      - .env
volumes:
  logs:
