version: 2.1
jobs:
  build-and-test:
    docker:
      - image: mongo:latest
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm i -g yarn
      - run: yarn
      - run: yarn test

workflows:
  build-and-test:
    jobs:
      - build-and-test
