version: 2.1
jobs:
  build:
    working_directory: ~/cougarcs-backend
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
workflows:
  build-and-test:
    jobs:
      - build
