name: Bug Report
description: Describe the bug A clear and concise description of what the bug is.
title: "[Bug]: "
labels: "bug"
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug!
- type: textarea
  id: reproduction
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  id: desktop
  attributes:
    label: Desktop
    description: Please complete the following information.
    value: |
      OS: [e.g. iOS]
      Browser [e.g. chrome, safari]
      Version [e.g. 22]
- type: textarea
  id: mobile
  attributes:
    label: Smartphone
    description: Please complete the following information.
    value: |
      Device: [e.g. iPhone6]
      OS: [e.g. iOS8.1]
      Browser [e.g. stock browser, safari]
      Version [e.g. 22]
- type: textarea
  id: context
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
    value: |
       Add any other additional context
